sudo: required
dist: trusty
language: python
python:
  - 3.6

before_install:
  - sudo apt-get update -qq

install:
  - pip install -U pip wheel codecov nox-automation

script:
  - nox -s unit implementations cover
  - codecov

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/download